### ISSUE TITLE
change seaweed based on comment likes

### ISSUE THREAD

**Issue by aholzer** [react-epfl/cross-aquarium#14]
in order to reflect if a comment's score is positive neutral or negative we could either have relative size of the weed, or have them change angle (in the pop version it might make more sense), or change the color (more or less bright for example)

@romaincazier (I know this is a last minute request, let me know what you think)

**Comment by romaincazier** [comment]
Again for this I relied on "voteScore". I decided to go with the variation of the leaves' size. The function to change the leaf's score is the same as the item's one "changeScore" (with again, an object with "._id" and "voteScore").

**Comment by ahgentil** [comment]
@romaincazier like you said you should rely on voteScore.
I updated now and you are not yet using the voteScore to change the leaves size right?
I don't see the function `changeCommentScore` being used yet.

**Comment by ahgentil** [comment]
I see that the rocks use the voteScore (although the the function is also called "changeCommentScore" 😄 )

**Comment by romaincazier** [comment]
I forgot to add the "voteScore" on comment creation. (now it's here)

The comments are actually inside the rocks, so that's why there is this function "changeCommentScore". But you just have to use "changeScore", it's more convenient. Nothing happens when using it ? The changes goes from [-5, 5] and reduce / augment the default size by 50%. (for the leaves)
